version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: backend
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app  # Mounts the backend code into the container
      - /app/__pycache__  # Prevents caching issues in Python

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app  # Mounts the frontend code into the container
      - /app/node_modules  # Prevents overwriting node_modules
    depends_on:
      - backend
